// Rotating pool of scheduled posts. Honest claims only, no invented stats.
// Rotation is date-derived (see route.ts) so it needs no persistent state.
export const SCHEDULED_POSTS: string[] = [
  "Every empty Solana token account is holding ~0.002 SOL hostage 🔒 We scan your wallet, close them, and send your SOL back. Non-custodial, live on mainnet. getbacksol.com",
  "Your wallet has more locked SOL than you think 👀 Every dead token account you never closed is still holding its rent deposit. Get it back: getbacksol.com",
  "Closing an empty Solana token account can't touch tokens that still hold value. It's enforced by the network itself, not a promise any app makes ✅ Reclaim yours: getbacksol.com",
  "No SOL left in your wallet? Doesn't matter 💸 GetBackSOL covers the network fee so you can still close dead accounts and walk away with SOL. getbacksol.com",
  "We show you the exact amount before you sign: gross, fee, net 📊 No surprises after the fact. Reclaim locked SOL: getbacksol.com",
  "GetBackSOL is live on Solana mainnet 🟢 Non-custodial, and has passed an external security audit. Check what your wallet is owed: getbacksol.com",
  "Airdrops, one-off swaps, memecoins you tried once 🎯 Every one of them left a dormant token account behind, still holding SOL. Go find them: getbacksol.com",
  "Got a wallet, a dApp, or just an audience that trusts you? Partner with GetBackSOL and earn 60% of every SOL your users reclaim 🤝 You never touch a key, we handle the rest. getbacksol.com/partners",
  "Bought a memecoin last cycle and forgot about it? The token may be gone, but its account is still open and still holding your rent deposit 🪦 getbacksol.com",
  "Solana never charges you rent on an empty token account. It just doesn't hand the deposit back until you close it 🔑 getbacksol.com",
  "Scanning your wallet costs nothing. You only pay a fee on SOL you actually get back 🔍 getbacksol.com",
  "Every token you've ever held opened an account. Every account locked up ~0.002 SOL. Most of them are still sitting there 📦 getbacksol.com",
  "Your keys never leave your wallet. We build the transaction, you review it, you sign it 🔐 getbacksol.com",
  "Closing dead token accounts is something you could do yourself. We just make it one click instead of one script ⚡ getbacksol.com",
  "NFT mints, airdrop claims, tokens that went to zero. Every one of them left an account behind holding SOL 🎨 getbacksol.com",
  "The network itself refuses to close any account that still holds tokens. That's not our promise, it's the protocol's rule ✅ getbacksol.com",
  "Leftover dust too small to bother selling used to block an account from closing. Safe-Burn clears it first 🔥 getbacksol.com",
  "We will never ask for your seed phrase. Nobody legitimate ever will 🚨 getbacksol.com",
  "Works with Phantom, Solflare and Backpack. Connect, scan, close 👛 getbacksol.com",
  "One transaction can close up to ten accounts at once. Less signing, less network fee ⚙️ getbacksol.com",
  "Reclaimed SOL goes straight from the closed account to your wallet. It never passes through us 🏦 getbacksol.com",
  "Wondering where your SOL keeps going? Some of it was never spent. It's locked in accounts you stopped using 🕵️ getbacksol.com",
  "Refer someone and you earn 60% of the fee on everything they reclaim, every time they do it 🤝 getbacksol.com",
  "No sign-up needed to earn referrals. Connect a wallet and your link is already waiting 🔗 getbacksol.com",
  "Weekly leaderboard with a real prize pool, funded by a share of the fees actually collected. Top 3 split it 🏆 getbacksol.com",
  "The prize pool isn't a number we made up. It's a cut of what the platform genuinely earned that week 📈 getbacksol.com",
  "New to how Solana rent works? We wrote the guide we wish had existed when we started 📖 getbacksol.com/blog",
  "GetBackSOL has passed an external security audit, and it stays non-custodial from start to finish 🛡️ getbacksol.com",
  "Empty wallet with no SOL for network fees? We cover the fee so you can still reclaim 💸 getbacksol.com",
  "You see the exact gross, fee and net before approving anything. Nothing gets deducted afterwards 🧾 getbacksol.com",
  "Traded across a few different DEXs this year? There's a good chance you've got a pile of dead accounts to close 🔄 getbacksol.com",
  "Spring cleaning for your Solana wallet. Close what's dead, keep the SOL 🧹 getbacksol.com",
  "That rent deposit was always yours. It's just been parked in an account you forgot about 💤 getbacksol.com",
  "It takes about thirty seconds. Connect, review the list, approve one transaction ⏱️ getbacksol.com",
  "Building a wallet or a Solana dApp? Our partner API pays 60% of the fee on every reclaim you send our way 🧩 getbacksol.com/partners",
  "Question about a transaction? We're on Telegram and usually answer quickly 💬 getbacksol.com/support",
  "Every reclaim is verifiable on Solscan, and we link the transaction for you 🔎 getbacksol.com",
  "Closing an account is permanent, but nothing of value can be lost doing it. Empty means empty ✔️ getbacksol.com",
  "That token that rugged is still costing you rent. Close the account and take the SOL back 📉 getbacksol.com",
  "Some dust is worth selling rather than burning. Turn on Sell dust and we'll route it through Jupiter 🔀 getbacksol.com",
  "Check first, decide after. The scan shows exactly what's reclaimable before you commit to anything 👀 getbacksol.com",
  "No account to create, no email, no password. Your wallet is the login 🚪 getbacksol.com",
  "Small amounts add up fast. A wallet sitting on thirty dead accounts is holding roughly 0.06 SOL 🧮 getbacksol.com",
];
