import type { Metadata } from "next";
import { SectionTitle } from "@/components/ui/Card";

const TITLE = "Terms of Service | GetBackSOL";
const DESCRIPTION = "The terms that apply when you use GetBackSOL to reclaim locked SOL.";

export const metadata: Metadata = {
  title: TITLE,
  description: DESCRIPTION,
  alternates: { canonical: "/terms" },
  openGraph: { title: TITLE, description: DESCRIPTION, url: "/terms" },
  twitter: { card: "summary_large_image", title: TITLE, description: DESCRIPTION },
  robots: { index: false, follow: true },
};

function H2({ children }: { children: React.ReactNode }) {
  return <h2 className="mt-8 mb-3 text-lg font-semibold tracking-tight">{children}</h2>;
}

function P({ children }: { children: React.ReactNode }) {
  return <p className="my-3 text-sm leading-relaxed text-[var(--muted)]">{children}</p>;
}

export default function TermsPage() {
  return (
    <div className="fade-in mx-auto max-w-2xl">
      <SectionTitle eyebrow="Legal" title="Terms of Service" description="Last updated July 2026." />

      <H2>1. What GetBackSOL is</H2>
      <P>
        GetBackSOL is a non-custodial tool that helps Solana wallet holders close dormant,
        zero-balance token accounts and reclaim the SOL rent deposit locked in them. A 15% service
        fee applies to the amount reclaimed, deducted automatically in the same transaction you
        approve.
      </P>

      <H2>2. Non-custodial, always</H2>
      <P>
        We never have access to your private key or seed phrase. Every transaction is built by our
        app but must be reviewed and signed by your own wallet before anything happens on-chain —
        we cannot execute a transaction without your explicit signature.
      </P>

      <H2>3. No guarantee of any specific amount</H2>
      <P>
        How much SOL you can reclaim depends entirely on your wallet&apos;s existing token
        accounts — something GetBackSOL has no control over. Network fees, token market conditions
        (relevant to the optional Sell feature), and Solana protocol rules are outside our control
        and can change at any time.
      </P>

      <H2>4. Fees</H2>
      <P>
        A 15% service fee applies to SOL reclaimed through the standard close/burn flow. The exact
        amount — gross, fee, and net — is shown before you sign anything, and the fee is deducted
        in the same atomic transaction as the reclaim itself, never afterward and never hidden.
      </P>

      <H2>5. Optional features</H2>
      <P>
        <b>Safe-Burn</b> permanently destroys residual token balances before closing an account —
        this is irreversible; burned tokens cannot be recovered under any circumstance.{" "}
        <b>Sell dust</b> attempts to swap dust tokens for SOL via Jupiter; results depend on market
        liquidity at the time and are never guaranteed. If no viable route exists, the token is
        burned instead.
      </P>

      <H2>6. Referral and partner program</H2>
      <P>
        Any connected wallet is automatically eligible to earn 60% of the fee generated by users it
        refers. Commission is calculated from the real, confirmed on-chain fee amount for every
        referred transaction — never a value that could be inflated or fabricated on either side —
        and paid automatically in the same transaction as the referred reclaim.
      </P>

      <H2>7. No investment, legal, or tax advice</H2>
      <P>
        GetBackSOL is a utility for recovering your own locked SOL — nothing on this site
        constitutes investment, legal, or tax advice. You&apos;re responsible for understanding any
        tax implications of reclaiming or selling assets in your own jurisdiction.
      </P>

      <H2>8. Assumption of risk</H2>
      <P>
        Interacting with any blockchain application carries inherent risk — software bugs, network
        congestion, wallet compatibility issues, and market volatility among them. You use
        GetBackSOL at your own risk and are responsible for reviewing every transaction in your
        wallet before signing it.
      </P>

      <H2>9. Acceptable use</H2>
      <P>
        You may not use GetBackSOL for any unlawful purpose, to interact with a wallet you do not
        own or are not authorized to act on, or to use the Partner API in a way that exceeds its
        documented, published rate limits.
      </P>

      <H2>10. Changes to these terms</H2>
      <P>
        We may update these terms as the product evolves. Continued use of GetBackSOL after a
        change means you accept the updated terms.
      </P>

      <H2>11. Limitation of liability</H2>
      <P>
        To the maximum extent permitted by law, GetBackSOL and its operators are not liable for
        indirect, incidental, or consequential damages arising from your use of the service.
      </P>

      <H2>12. Contact</H2>
      <P>
        Questions about these terms: reach us on{" "}
        <a href="https://telegram.me/GetBackSOL" className="text-[var(--accent)] hover:underline">
          Telegram
        </a>
        .
      </P>
    </div>
  );
}
